Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -60,4 +60,8 @@ jobs:
          echo "::set-output name=low::$LOW"
 
      
-    
+     - name: Fail on critical vulnerabilities
+       if: steps.count_vulns.outputs.critical != '0'
+       run: |
+         echo "Scan failed due to critical vulnerabilities."
+         exit 1
